version: "3"
   
services:
  db:
    build: ./db_instance/
    environment:
      - POSTGRES_PASSWORD=Pass2020!
    ports: 
      - 5432:5432
  bot:
    build: .
    command: python main.py
    volumes:
      - ./src/:/code
    depends_on:
      - db