[main]
member_join_with_default_role = "{member_mention} has joined the server and received the {default_role_name} role"
member_join = "{member_mention} has joined the server"

vm_slave_deleted = "{user_mention} has deleted a VM slave"
vm_slave_created = "{user_mention} has created a VM slave"

guild_already_setup = "This server is already set up"
guild_setup_complete = "This server has now been initialised"

[logging]
channel_set = "Logging channel has been set to <#{channel_id!s}>"
channel_set_already = "Logging channel already set to this channel"
channel_set_notify_in_channel = "{author_mention} has set this channel as the logging channel"

channel_get = "Logging channel is set to <#{channel_id!s}>"
channel_get_notfound = "Logging channel has not been set"

channel_removed = "Log channel has been removed"

[admin]
channel_cleared = "{author_mention} has cleared {message_amount} messages from {author_mention}"
members = "This server has {member_count} members including me"

[default_role]
default_role_missing = "Default role has not been set"

default_role_set = "Default role has been set to {role_id}"
default_role_set_log = "{author} has set the default role to {role_mention}"
default_role_set_missing_param = "You need to either @ a role or paste the ID"

default_role_get = "Default role is set to {role_id}"

default_role_removed = "Default role has been removed"
default_role_removed_log = "{author_mention} has removed the default role"